# Generated by Django 5.0.3 on 2024-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_blogspage_checkoutpage_clientpage_destinationpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='checkoutpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='clientpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='clientpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='destinationpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='experiencepage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='experiencepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogsPage',
        ),
        migrations.DeleteModel(
            name='CheckoutPage',
        ),
        migrations.DeleteModel(
            name='ClientPage',
        ),
        migrations.DeleteModel(
            name='DestinationPage',
        ),
        migrations.DeleteModel(
            name='ExperiencePage',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
